name: build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        shell: powershell
        run: .\build.ps1
      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: mgba-fomt-mine-xray-windows
          path: |
            MineXRayHDOverlay.exe
            OpenGbaWithLatestSave.exe

